In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [97]:
chicago_avg_price_gas = pd.read_csv("chicago_avg_price_gas.csv")
chicago_cta_daily_boarding = pd.read_csv("chicago_cta_daily_boarding.csv")
chicago_weather_2425 = pd.read_csv("chicago_weather_2425.csv")

In [98]:
chicago_weather_2425

,STATION,DATE,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT10,WT11
0,US1ILDP0139,2025-06-20,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1ILDP0139,2025-06-25,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1ILDP0139,2025-06-26,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1ILDP0139,2025-07-07,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1ILDP0139,2025-07-09,0.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91834,USC00111577,2025-12-27,0.00,0.0,0.0,NaN,45.0,38.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91835,USC00111577,2025-12-28,1.12,0.0,0.0,NaN,59.0,22.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
91836,USC00111577,2025-12-29,0.02,0.9,1.0,NaN,24.0,14.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
91837,USC00111577,2025-12-30,0.03,0.9,2.0,NaN,25.0,10.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91838,USC00111577,2025-12-31,0.03,0.1,0.0,NaN,35.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
chicago_weather_2425['DATE'] = pd.to_datetime(chicago_weather_2425['DATE'])
weather_small = chicago_weather_2425[['DATE', 'PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN',
                                      'WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06',
                                      'WT07', 'WT08', 'WT09', 'WT10', 'WT11']]

weather_daily = weather_small.groupby('DATE')[['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN']].mean()
weather_events = weather_small.groupby('DATE')[['WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06',
                                                'WT07', 'WT08', 'WT09', 'WT10', 'WT11']].max()
weather_daily = pd.concat([weather_daily, weather_events], axis=1).reset_index()
weather_daily['month'] = weather_daily['DATE'].dt.to_period('M')

weather_monthly = weather_daily.groupby('month')[['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN',
                                                  'WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06',
                                                  'WT07', 'WT08', 'WT09', 'WT10', 'WT11']].mean().reset_index()
weather_monthly = weather_monthly[weather_monthly['month'] <= '2025-11']
weather_monthly = weather_monthly.rename(columns={'WT01': 'fog',
                                                  'WT02': 'heavy_fog',
                                                  'WT03': 'thunder',
                                                  'WT04': 'ice_pellets_sleet_small_hail',
                                                  'WT05': 'hail',
                                                  'WT06': 'glaze_or_rime',
                                                  'WT07': 'dust_volcanic_ash_blowing_dust_sand',
                                                  'WT08': 'smoke_or_haze',
                                                  'WT09': 'blowing_or_drifting_snow',
                                                  'WT10': 'tornado_waterspout_funnel_cloud',
                                                  'WT11': 'high_or_damaging_winds'})

,month,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT10,WT11
0,2024-01,0.128897,0.440159,2.509872,26.193548,30.561636,21.258065,1.0,1.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0
1,2024-02,0.023022,0.046524,0.065023,39.137931,48.443966,28.939655,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0
2,2024-03,0.139756,0.017691,0.016489,43.645161,52.610599,34.305876,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
3,2024-04,0.162107,0.000590,0.000000,52.800000,61.283333,42.895833,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0
4,2024-05,0.147641,0.000000,0.000000,64.903226,74.689516,53.665323,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0
5,2024-06,0.150780,0.000000,0.000000,74.033333,83.121429,63.682738,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0
6,2024-07,0.175625,0.000000,0.000000,74.548387,82.956797,65.511521,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1.0
7,2024-08,0.109436,0.000000,0.000000,74.451613,82.974078,64.846774,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
8,2024-09,0.069577,0.000000,0.015278,70.600000,79.390476,59.564881,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
9,2024-10,0.045896,0.000000,0.000000,59.774194,69.881336,47.753456,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
10,2024-11,0.114420,0.074778,0.012903,46.333333,52.345833,39.548810,1.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN
11,2024-12,0.063332,0.067515,0.166260,32.451613,38.141129,25.161290,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
12,2025-01,0.030658,0.151444,0.540778,23.548387,29.830645,14.608871,1.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0,1.0,NaN,NaN
13,2025-02,0.044566,0.156023,0.904336,27.738095,34.477679,19.544643,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0
14,2025-03,0.122284,0.060999,0.050625,44.301075,54.350806,33.641129,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0
15,2025-04,0.104208,0.000000,0.000000,50.800000,59.508333,40.787500,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
16,2025-05,0.065958,0.000000,0.000000,57.602151,67.079493,48.270161,1.0,NaN,1.0,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0
17,2025-06,0.120362,0.000000,0.000000,73.811111,82.879167,63.383333,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
18,2025-07,0.173762,0.000000,0.000000,77.784946,85.804724,68.524194,1.0,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0
19,2025-08,0.182136,0.000000,0.000000,74.413793,81.692396,64.526498,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
20,2025-09,0.041414,0.000000,0.000000,69.071429,78.816071,58.325000,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2025-10,0.087369,0.000000,0.000000,58.397849,66.403802,49.554147,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2025-11,0.083097,0.372363,0.492531,42.888889,49.645833,34.470833,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [81]:
chicago_cta_daily_boarding['service_date'] = pd.to_datetime(chicago_cta_daily_boarding['service_date'])
chicago_cta_daily_boarding = chicago_cta_daily_boarding.sort_values(by = 'service_date')
chicago_cta_daily_boarding = chicago_cta_daily_boarding[(chicago_cta_daily_boarding['service_date'].dt.year >= 2024) 
                                                        & (chicago_cta_daily_boarding['service_date'].dt.year <= 2026)]
chicago_cta_daily_boarding['month'] = chicago_cta_daily_boarding['service_date'].dt.to_period('M')
cta_monthly = chicago_cta_daily_boarding.groupby('month')[['bus', 'rail_boardings', 'total_rides']].sum().reset_index()
daytype_counts = pd.crosstab(chicago_cta_daily_boarding['service_date'].dt.to_period('M'),
                            chicago_cta_daily_boarding['day_type']).reset_index()
daytype_counts = daytype_counts.rename(columns = {'service_date' : 'month'})
chicago_cta_monthly_boarding = pd.merge(cta_monthly, daytype_counts, on = 'month')
chicago_cta_monthly_boarding = chicago_cta_monthly_boarding.rename(columns = {'A': 'total_saturdays', 
                                                                              'U' : 'sunday_or_holiday', 
                                                                              'W' : 'total_weekdays'})
chicago_cta_monthly_boarding

,month,bus,rail_boardings,total_rides,total_saturdays,sunday_or_holiday,total_weekdays
0,2024-01,12883065,8552283,21435348,4,5,22
1,2024-02,14408475,9300019,23708494,4,4,21
2,2024-03,14794052,10107439,24901491,5,5,21
3,2024-04,15615211,10458339,26073550,4,4,22
4,2024-05,16367601,11330441,27698042,4,5,22
5,2024-06,14742769,10928671,25671440,5,5,20
6,2024-07,15306884,11279758,26586642,4,5,22
7,2024-08,15534600,11744693,27279293,5,4,22
8,2024-09,16161092,11665977,27827069,4,6,20
9,2024-10,17514190,12630875,30145065,4,4,23
10,2024-11,14700298,10312595,25012893,5,5,20
11,2024-12,13705388,9152319,22857707,4,6,21
12,2025-01,13762257,9152197,22914454,4,5,22
13,2025-02,13725525,8781408,22506933,4,4,20
14,2025-03,15565051,10668550,26233601,5,5,21
15,2025-04,16281859,11247435,27529294,4,4,22
16,2025-05,16357704,11775315,28133019,5,5,21
17,2025-06,15096977,11828838,26925815,4,5,21
18,2025-07,15407467,12403716,27811183,4,5,22
19,2025-08,16263989,12970077,29234066,5,5,21
20,2025-09,16720898,12732813,29453711,4,5,21
21,2025-10,17126989,13324046,30451035,4,4,23
22,2025-11,14264012,10616667,24880679,5,6,19

In [83]:
capg = chicago_avg_price_gas.rename(columns = {'observation_date' : 'month', 'APUS23A7471A' : 'avg_gas_price'})
capg['month'] = pd.to_datetime(capg['month']).dt.to_period('M')
capg = capg[capg['month'] <= '2025-11'] # because 2025-12 and 2026-01 don't exist in chicago_cta_monthly_boarding
capg

      month  avg_gas_price
0   2024-01          3.326
1   2024-02          3.583
2   2024-03          4.009
3   2024-04          4.202
4   2024-05          4.233
5   2024-06          4.155
6   2024-07          4.226
7   2024-08          4.092
8   2024-09          3.729
9   2024-10          3.635
10  2024-11          3.414
11  2024-12          3.428
12  2025-01          3.434
13  2025-02          3.412
14  2025-03          3.491
15  2025-04          3.608
16  2025-05          3.593
17  2025-06          3.661
18  2025-07          3.673
19  2025-08          3.671
20  2025-09          3.679
21  2025-10            NaN
22  2025-11          3.461