In [6]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [8]:
chicago_avg_price_gas = pd.read_csv("original_data\chicago_avg_price_gas.csv")
chicago_cta_daily_boarding = pd.read_csv("original_data\chicago_cta_daily_boarding.csv")
chicago_weather_2425 = pd.read_csv("original_data\chicago_weather_2425.csv")

In [3]:
chicago_avg_price_gas

   observation_date  APUS23A7471A
0        2024-01-01         3.326
1        2024-02-01         3.583
2        2024-03-01         4.009
3        2024-04-01         4.202
4        2024-05-01         4.233
5        2024-06-01         4.155
6        2024-07-01         4.226
7        2024-08-01         4.092
8        2024-09-01         3.729
9        2024-10-01         3.635
10       2024-11-01         3.414
11       2024-12-01         3.428
12       2025-01-01         3.434
13       2025-02-01         3.412
14       2025-03-01         3.491
15       2025-04-01         3.608
16       2025-05-01         3.593
17       2025-06-01         3.661
18       2025-07-01         3.673
19       2025-08-01         3.671
20       2025-09-01         3.679
21       2025-10-01           NaN
22       2025-11-01         3.461
23       2025-12-01         3.229
24       2026-01-01         3.100

In [9]:
chicago_cta_daily_boarding

     service_date day_type      bus  rail_boardings  total_rides
0      02/01/2010        W  1091041          648428      1739469
1      07/15/2006        A   603018          412144      1015162
2      08/26/2017        A   487453          446049       933502
3      12/25/2007        U   249699          111582       361281
4      07/08/2005        W   950222          591325      1541547
...           ...      ...      ...             ...          ...
9095   10/27/2025        W   550654          396777       947431
9096   10/28/2025        W   638531          464085      1102616
9097   10/29/2025        W   645197          467094      1112291
9098   10/30/2025        W   645207          476146      1121353
9099   10/31/2025        W   601396          432500      1033896

[9100 rows x 5 columns]

In [10]:
chicago_weather_2425

,STATION,DATE,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT10,WT11
0,US1ILDP0139,2025-06-20,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1ILDP0139,2025-06-25,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1ILDP0139,2025-06-26,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1ILDP0139,2025-07-07,1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1ILDP0139,2025-07-09,0.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91834,USC00111577,2025-12-27,0.00,0.0,0.0,NaN,45.0,38.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91835,USC00111577,2025-12-28,1.12,0.0,0.0,NaN,59.0,22.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
91836,USC00111577,2025-12-29,0.02,0.9,1.0,NaN,24.0,14.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
91837,USC00111577,2025-12-30,0.03,0.9,2.0,NaN,25.0,10.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91838,USC00111577,2025-12-31,0.03,0.1,0.0,NaN,35.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN