In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [10]:
# eda 
df = pd.read_csv(r"C:\Users\lyons\OneDrive\Desktop\is477\IS477_Tran_Machin_Lee\eda\merged_datasets.csv")
df

,month,bus,rail_boardings,total_rides,total_saturdays,total_sunday_or_holiday,total_weekdays,PRCP,SNOW,SNWD,...,thunder,ice_pellets_sleet_small_hail,hail,glaze_or_rime,dust_volcanic_ash_blowing_dust_sand,smoke_or_haze,blowing_or_drifting_snow,tornado_waterspout_funnel_cloud,high_or_damaging_winds,avg_gas_price
0,2024-01,12883065,8552283,21435348,4,5,22,0.128897,0.440159,2.509872,...,0.0,4.0,1.0,4.0,0.0,9.0,2.0,0.0,1.0,3.223
1,2024-02,14408475,9300019,23708494,4,4,21,0.023022,0.046524,0.065023,...,5.0,1.0,3.0,1.0,0.0,11.0,0.0,0.0,1.0,3.483
2,2024-03,14794052,10107439,24901491,5,5,21,0.139756,0.017691,0.016489,...,6.0,1.0,1.0,0.0,0.0,5.0,0.0,0.0,0.0,3.910
3,2024-04,15615211,10458339,26073550,4,4,22,0.162107,0.000590,0.000000,...,13.0,2.0,3.0,1.0,0.0,4.0,0.0,0.0,2.0,4.103
4,2024-05,16367601,11330441,27698042,4,5,22,0.147641,0.000000,0.000000,...,18.0,0.0,3.0,0.0,0.0,8.0,0.0,0.0,2.0,4.133
5,2024-06,14742769,10928671,25671440,5,5,20,0.150780,0.000000,0.000000,...,11.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,2.0,4.053
6,2024-07,15306884,11279758,26586642,4,5,22,0.175625,0.000000,0.000000,...,9.0,0.0,1.0,0.0,0.0,7.0,0.0,1.0,4.0,4.123
7,2024-08,15534600,11744693,27279293,5,4,22,0.109436,0.000000,0.000000,...,10.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,3.985
8,2024-09,16161092,11665977,27827069,4,6,20,0.069577,0.000000,0.015278,...,4.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,3.617
9,2024-10,17514190,12630875,30145065,4,4,23,0.045896,0.000000,0.000000,...,4.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,3.524
10,2024-11,14700298,10312595,25012893,5,5,20,0.114420,0.074778,0.012903,...,0.0,0.0,1.0,0.0,0.0,7.0,1.0,0.0,0.0,3.303
11,2024-12,13705388,9152319,22857707,4,6,21,0.063332,0.067515,0.166260,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.317
12,2025-01,13762257,9152197,22914454,4,5,22,0.030658,0.151444,0.540778,...,1.0,1.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,3.324
13,2025-02,13725525,8781408,22506933,4,4,20,0.044566,0.156023,0.904336,...,1.0,1.0,1.0,4.0,0.0,7.0,0.0,0.0,1.0,3.302
14,2025-03,15565051,10668550,26233601,5,5,21,0.122284,0.060999,0.050625,...,8.0,3.0,3.0,0.0,0.0,6.0,0.0,0.0,3.0,3.382
15,2025-04,16281859,11247435,27529294,4,4,22,0.104208,0.000000,0.000000,...,6.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,3.499
16,2025-05,16357704,11775315,28133019,5,5,21,0.065958,0.000000,0.000000,...,6.0,0.0,2.0,0.0,1.0,5.0,0.0,0.0,2.0,3.483
17,2025-06,15096977,11828838,26925815,4,5,21,0.120362,0.000000,0.000000,...,12.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,3.550
18,2025-07,15407467,12403716,27811183,4,5,22,0.173762,0.000000,0.000000,...,15.0,0.0,0.0,0.0,1.0,12.0,0.0,0.0,2.0,3.561
19,2025-08,16263989,12970077,29234066,5,5,21,0.182136,0.000000,0.000000,...,10.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,2.0,3.559
20,2025-09,16720898,12732813,29453711,4,5,21,0.041414,0.000000,0.000000,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.566
21,2025-10,17126989,13324046,30451035,4,4,23,0.087369,0.000000,0.000000,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.331
22,2025-11,14264012,10616667,24880679,5,6,19,0.083097,0.372363,0.492531,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.346

In [9]:
df.describe()

,bus,rail_boardings,total_rides,total_saturdays,total_sunday_or_holiday,total_weekdays,PRCP,SNOW,SNWD,TAVG,...,thunder,ice_pellets_sleet_small_hail,hail,glaze_or_rime,dust_volcanic_ash_blowing_dust_sand,smoke_or_haze,blowing_or_drifting_snow,tornado_waterspout_funnel_cloud,high_or_damaging_winds,avg_gas_price
count,2.300000e+01,2.300000e+01,2.300000e+01,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,...,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000
mean,1.531767e+07,1.099846e+07,2.631612e+07,4.347826,4.826087,21.260870,0.103752,0.060352,0.207569,54.749133,...,6.347826,0.608696,0.869565,0.608696,0.086957,5.434783,0.173913,0.043478,1.173913,3.594652
std,1.195546e+06,1.380155e+06,2.500868e+06,0.486985,0.650327,1.009833,0.049530,0.119135,0.551711,17.531416,...,5.192728,1.076152,1.140349,1.269901,0.288104,3.975220,0.491026,0.208514,1.114050,0.299227
min,1.288306e+07,8.552283e+06,2.143535e+07,4.000000,4.000000,19.000000,0.023022,0.000000,0.000000,23.548387,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.223000
25%,1.455439e+07,1.021002e+07,2.489108e+07,4.000000,4.000000,21.000000,0.064645,0.000000,0.000000,43.267025,...,2.000000,0.000000,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000,0.000000,3.338500
50%,1.540747e+07,1.124744e+07,2.658664e+07,4.000000,5.000000,21.000000,0.109436,0.000000,0.000000,57.602151,...,6.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,1.000000,3.524000
75%,1.627292e+07,1.180208e+07,2.781913e+07,5.000000,5.000000,22.000000,0.143698,0.064257,0.057824,72.205556,...,10.000000,1.000000,1.000000,0.500000,0.000000,8.000000,0.000000,0.000000,2.000000,3.763500
max,1.751419e+07,1.332405e+07,3.045104e+07,5.000000,6.000000,23.000000,0.182136,0.440159,2.509872,77.784946,...,18.000000,4.000000,3.000000,4.000000,1.000000,12.000000,2.000000,1.000000,4.000000,4.133000

# DON"T DELETE THIS... use in final submission later
We pivoted from our original monthly Chicago gasoline-price dataset. The original dataset reported prices for all types of gasoline, but we decided this was less appropriate for our analysis for two main reasons. First, our target demographic is more closely represented by the price of regular gasoline, since that is the fuel type most likely to reflect the everyday driving costs faced by typical consumers. Second, the all-types gasoline dataset contained a missing value for October 2025, which created an avoidable data issue during merging and analysis. Because of this, we switched to a monthly Chicago regular gasoline price series, which is both more relevant to our research question and more complete for the time period we study.